### ISSUE TITLE
Why 'Jeff'?

### ISSUE THREAD

**Issue by replete** [oskarcieslik/Jeff#1]
Brb, just _jeffing_ my license.

**Comment by rpunkfu** [comment]
Hi @replete! :smiley:

this -> https://www.youtube.com/watch?v=AfIOBLr1NDU :smiley:

**Comment by replete** [comment]
Hahaha, brilliant. Funnily enough, just an hour ago I watched a 'vines compilation' on Youtube, and had to search for the source of the reference.
